% Write a program in MATLAB to find the volume of the solid generated by revolving the region bounded by the curve y = 4 /(x^2 + 4) , and the lines x = 0 and x = 2 about the X-axis.
% Print the output as a symbolic value as well as in double precision.
% Also plot the surface of this solid, label the X-axis, Y -axis and Z-axis and title the graph.
  
clear;
clc;

syms x

y(x) = 4 / (x^2 + 4);

yr=0;

I=[0,2];
a=I(1);
b=I(2);

vol = pi * int((y(x) - yr)^2, a, b);

disp('Volume of solid of revolution is: ');
disp(vol);
disp('Which is equal to: ')
disp(round(vol, 2));

yx=matlabFunction(y);
xv = linspace(a,b,101);

[X,Y,Z] = cylinder(yx(xv)-yr);
Z = a+Z.*(b-a);

surf(Z,Y+yr,X);
hold on;
plot([a b],[yr yr],'-r','LineWidth',2);
view(22,11);
xlabel('X-Axis')
ylabel('Y-Axis')
title('Question 1 Graph')
